### ISSUE TITLE
OpenStreetMap-Widget (and others?):  No flush on new search

### ISSUE THREAD

**Issue by mkemmann** [LaxarJS/finder-demo#3]
If you change the term of the search input field and the "Open Street Map"-Widget does not find a match, it still shows the content of the previous search.

I would expect that all related widgets are set to "empty" in that case, respectively that all widgets are flushed in principle before displaying the result of a new search.

**Comment by alex3683** [comment]
Fixed on `master` (`v1.2.0`).

**Comment by mkemmann** [comment]
thx. :-)
